### ISSUE TITLE
[Feat][RP] SPID button random ordering of entities

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-django#110]
here:
https://github.com/italia/spid-cie-oidc-django/blob/main/spid_cie_oidc/relying_party/views.py#L588

we just need to implement a shuffle method to randomize the elements ordering inside of a list

[@mauro](https://github.com/mmariuzzo) ^

**Comment by peppelinux** [comment]
````
import random

random.shuffle(providers)
````

**Comment by dezhizhang1985** [comment]
done here https://github.com/italia/spid-cie-oidc-django/pull/121
