### ISSUE TITLE
Fix: wrong logo_url in the sample op

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-django#137]
The sample op contained in the example dumps contains a logo url (http://127.0.0.1:8000/oidc/op/statics/logo.svg) that gives 404 when used in an external RP.

**Comment by peppelinux** [comment]
We need to remove this constant in the code
https://github.com/italia/spid-cie-oidc-django/blob/main/spid_cie_oidc/relying_party/templates/rp_landing.html#L57

and use the logo_uri contained in the OP metadata

we also need to update the example data, removing the wrong webpath and using a real one, for example
log_uri: "http://127.0.0.1:8000/oidc/op/static/svg/lspid-logo-c-lb.svg"

**Comment by peppelinux** [comment]
done here:
https://github.com/italia/spid-cie-oidc-django/pull/129/commits/2e5cfb40e67a27a1c09629fe9915af3fcdbb03aa
