### ISSUE TITLE
[Tools] forms are not protected with a correct exception handling

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-django#159]
Please @dezhizhang1985 check all the form and handle the exceptions with unit tests.
submit fake and corrupt data and check the behaviour of the page

![image](https://user-images.githubusercontent.com/1297620/158907784-3f2aa3de-c384-439a-9eb3-19328ce83848.png)

**Comment by dezhizhang1985** [comment]
done here: https://github.com/italia/spid-cie-oidc-django/pull/161
