### ISSUE TITLE
[Docs] OpenID Connect Provider

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-django#16]
We need to document how to get a working oidc provider

**Comment by peppelinux** [comment]
Which settings parameters are required to configure a oidc provider?
which action we must do to get it to work?
- create an entity
- create or obtain autoamtically a jwk
- put a metadata

**Comment by peppelinux** [comment]
Here's the piece of documentation to complete
https://github.com/peppelinux/spid-cie-oidc-django/blob/provider/docs/technical_specifications/PROVIDER.md

**Comment by francescatronconi** [comment]
in example provider:
-  cancello la base dati
- faccio migrate
- configuro una federation entity configuration OP
- nel settings configuro profilo cie

in example federation:
- configuro l'OP cie come federation descendant

entrambe i progetti devono essere runnati: 8000 e 8002(./manage.py runserver 0.0.0.0:8002)

- aggiungi OP nella configurazione del RP (oidc_fed_identity_o
- vado su service provider e  faccio fetch
- vado landing page RP e clicco su bottone cie

**Comment by peppelinux** [comment]
Done here
https://github.com/italia/spid-cie-oidc-django/blob/dev/docs/technical_specifications/PROVIDER.md
