### ISSUE TITLE
Django >= 4.0  error for RP (on OpenSuse 15.3)

### ISSUE THREAD

**Issue by longstoned** [italia/spid-cie-oidc-django#169]
Hello,

not Django/Python expert.
Trying to follow instruction here 
https://github.com/italia/spid-cie-oidc-django/blob/main/docs/SETUP.md

for a basic Spid OIDC RP, 
I'm getting this:

```
pip install spid-cie-oidc
Defaulting to user installation because normal site-packages is not writeable
Collecting spid-cie-oidc
  Using cached spid_cie_oidc-0.4.16-py3-none-any.whl (436 kB)
Collecting pydantic
  Using cached pydantic-1.9.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.0 MB)
ERROR: Could not find a version that satisfies the requirement Django>=4.0 (from spid-cie-oidc) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29, 2.0a1, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.12, 2.0.13, 2.1a1, 2.1b1, 2.1rc1, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.2a1, 2.2b1, 2.2rc1, 2.2, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.20, 2.2.21, 2.2.22, 2.2.23, 2.2.24, 2.2.25, 2.2.26, 2.2.27, 3.0a1, 3.0b1, 3.0rc1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.1a1, 3.1b1, 3.1rc1, 3.1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.2a1, 3.2b1, 3.2rc1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.2.11, 3.2.12)
ERROR: No matching distribution found for Django>=4.0 (from spid-cie-oidc)

```
Is 4.0+ really necessary ?
Looked some official repos but seems not available (Opensuse 15.3 here)

Thanks.

Diego

**Comment by peppelinux** [comment]
Please use a virtualenv or install It via pip as root

It works also with Django 3 but we wont support it

**Comment by longstoned** [comment]
Hi. Tried something like what listed on page but not working.
is it possible to show here or there the exact commands?
I did:
- virtualenv -p python3 env (as root)
- git clone https://github.com/peppelinux/spid-cie-oidc-django
- git clone https://github.com/peppelinux/spid-cie-oidc-django
- cd spid-cie-oidc-django
- pip install --upgrade pip (--> Requirement already satisfied: pip in /home/diegone/GIT7/env/lib/python3.6/site-packages (21.3.1))
- pip install -e .   (--> ERROR: Could not find a version that satisfies the requirement Django>=4.0 (from spid-cie-oidc) )  (same output)


Sorry but not a python expert at all ,and was looking for a set and forget spidOIDC RP

**Comment by longstoned** [comment]
Also tried (first) with these as root
:
- pip install spid-cie-oidc
- pip3 install spid-cie-oidc

**Comment by peppelinux** [comment]
Please don't use python3.6, unfortunately it is EOL nowaday.
At least py37

it seems that your python interpreter is deprecated for Django 4.
Please type python and check what version you're using

**Comment by peppelinux** [comment]
You can even use the docker-compose to have a working platform for non-development need

**Comment by longstoned** [comment]
output for pyhton:

python
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.

btw, there's some how-to for the docker option?

**Comment by peppelinux** [comment]
https://github.com/italia/spid-cie-oidc-django#docker-compose

**Comment by longstoned** [comment]
Hi Giuseppe.
Very kind to ask. I meant to reply and try your suggestions these days, but
had a reallocation of tasks and could not proceed, even if interested.

I may retry in a couple weeks, possibly.
One question though:
When is the final 1.0 or at least.. the minimal, normative-bound and valid
Milestone due?

Am I correct saying that I read it was planned, like a couple of weeks from
now?

Thanks for you interest.

Diego

Il mar 22 mar 2022, 17:43 Giuseppe De Marco ***@***.***> ha
scritto:

**Comment by peppelinux** [comment]
This 0.4.0 is stable, we'll go ahead this week for 0.5.0.
the 0.6.0 will only have QaD tests if AgID and IPZS defines a spec document, otherwise we'll stay on hold

All to say that we have a stable release without a compliant SSO/ACR-refresh-token policy (https://github.com/italia/spid-cie-oidc-django/issues/123) and this bug (https://github.com/italia/spid-cie-oidc-django/issues/170)

all the other are minor bugs. the v0.5.0 will fix all these and improve the documentation

**Comment by peppelinux** [comment]
Hi,

we consolidated the docker-compose with all the example projects up and running
