### ISSUE TITLE
[onboarding] additional fields in registration form

### ISSUE THREAD

**Issue by dezhizhang1985** [italia/spid-cie-oidc-django#175]
Missing fields of the entity registration form:

- [ ] ~IPA code or VAT number, that determines whether the participant is public or private~
- [ ] ~at least one administrative email contact~
- [x] SPID/CIE authentication request trigger url at the onboarding system testing OP

**Comment by peppelinux** [comment]
@dezhizhang1985 we won't implement the first two but the url that trigger the auth (not required, it can be null).

I've included this issue in the milestone v0.6.0

**Comment by dezhizhang1985** [comment]
done here: https://github.com/italia/spid-cie-oidc-django/pull/189
