### ISSUE TITLE
Djagger: endpoint without a pydantic schema need to be excluded

### ISSUE THREAD

**Issue by francescatronconi** [italia/spid-cie-oidc-django#191]
In http://localhost:8000/rest/api/docs only endpoint with schema pydantic should be visualized

**Comment by peppelinux** [comment]
We made a PR here with our proposal
https://github.com/royhzq/djagger/pull/5

We're going to document all the SPID/CIE OIDC Endpoints, Federation included, in OAS3
![image](https://user-images.githubusercontent.com/1297620/160614469-733c86bb-8f4c-4f1b-9b32-695028c056c9.png)

This contribution will be reflected also here:
https://bitbucket.org/openid/connect/issues/1414/federation-api-endpoints-with-openapi

@francescatronconi we need to put a section in our README regarding this web resource (reDoc)

**Comment by peppelinux** [comment]
Our contribution have been accepted, we have to wait for a new release

https://github.com/royhzq/djagger/pull/5#issuecomment-1088361060

**Comment by peppelinux** [comment]
Release done here @francescatronconi 
https://github.com/royhzq/djagger/releases/tag/1.1.2

We can close this issue right now :)
