### ISSUE TITLE
403 from introspection endpoint

### ISSUE THREAD

**Issue by damikael** [italia/spid-cie-oidc-django#199]
The response to a well formed introspection request returns with 403 error https status code and reason "CSRF cookie not set."

**Comment by peppelinux** [comment]
that's something patched in the dev branch, here
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/provider/views/introspection_endpoint.py#L41

we have the except of csrf token as we can see.
May you're using the main branch?

Hopefully tomorrow we'll have a new release

**Comment by peppelinux** [comment]
Done in v0.6.0
