### ISSUE TITLE
[Bug] State parameter is not returned in case of error

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-django#203]
In case of authentication error, the state parameter is not returned to the RP redirect URI.
You could reproduce it, for example, by clicking "Cancel" on the login form, no "state" querystring parameter will be returned to the RP

**Comment by peppelinux** [comment]
Done here
https://github.com/italia/spid-cie-oidc-django/pull/205#pullrequestreview-927199386

**Comment by danielegiallonardo** [comment]
Verified. The issue can be closed
