### ISSUE TITLE
[Heroku Deployment] REQUEST REJECTED: Value too long for type character varying(2048)

### ISSUE THREAD

**Issue by alessia7** [italia/spid-cie-oidc-django#229]
I deployed the examples/federation project on Heroku. The admin page works but the landing page, after clicking the provider, reports the following error:

   "REQUEST REJECTED
   ('value too long for type character varying(2048)\ n') "

Anyone have the same problem?

![Immagine heroku spid](https://user-images.githubusercontent.com/49901951/163669883-afad17fa-c4d9-4c5a-b86f-ca821ae1c728.jpg)

**Comment by peppelinux** [comment]
It's a database error

Which db and which versione of this project are you deploying?

Give me the details, we'll fix this issue together

**Comment by peppelinux** [comment]
I think that the problema Is here
https://github.com/italia/spid-cie-oidc-django/blob/2e0b6071c22580911b6f0a4274084435bb6ab0ba/spid_cie_oidc/provider/models.py#L30

I dont think to exceer the 2048 length in authz request.

Can you Copy It here?
I leaved all the req params also as Get params, outsider of request, for debug purpose. If the problema Is this we can made a cleanup

**Comment by alessia7** [comment]
I have the latest version.
I don't deploy spid-cie-oidc because I install it with requirements via pip.
I have these requirements : 

aiohttp==3.8.1
aiosignal==1.2.0
asgiref==3.5.0
astroid==2.11.2
async-timeout==4.0.2
attrs==21.4.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.2
cryptojwt==1.7.1
design-django-theme==1.6.0
dill==0.3.4
dj-database-url==0.5.0
djagger==1.1.1
Django==4.0.3
django-appconf==1.0.5
django-compressor==3.1
django-heroku==0.3.1
django-sass-processor==1.1
djangorestframework==3.13.1
dnspython==2.2.1
email-validator==1.1.3
frozenlist==1.3.0
gunicorn==20.1.0
idna==3.3
isort==5.10.1
lazy-object-proxy==1.7.1
libsass==0.21.0
mccabe==0.7.0
multidict==6.0.2
platformdirs==2.5.1
psycopg2==2.9.3
psycopg2-binary==2.9.3
pycparser==2.21
pydantic==1.9.0
pylint==2.13.5
pytz==2022.1
rcssmin==1.1.0
requests==2.27.1
rjsmin==1.2.0
six==1.16.0
-e git+https://github.com/italia/spid-cie-oidc-django.git@320c9f63b63ca940b5085787fe700003b0fe78a6#egg=spid_cie_oidc
sqlparse==0.4.2
tomli==2.0.1
typing_extensions==4.1.1
urllib3==1.26.9
whitenoise==6.0.0
wrapt==1.14.0
yarl==1.7.2

**Comment by peppelinux** [comment]
Please install the last stable version, consider that you have a docker-compose for demo/test

Please copy your authz request here (the usr triggered when you hit the auth button)

which version of spid-cie-oidc-django have you tested?

**Comment by peppelinux** [comment]
anyway I made a cleanup of authz parameters in v0.6.8, here
https://github.com/italia/spid-cie-oidc-django/pull/230

hope it helps

**Comment by peppelinux** [comment]
Hi @alessia7 
is there any update for this issue?

**Comment by alessia7** [comment]
After cleanup, with v.0.6.8 version, my problem is not solved. 
With Docker works, but with Heroku not, and the issue is always the same. 

There are also errors like this one during the './manage loaddata dumps/example.json' command:

   django.db.utils.DataError: Problem installing fixture '/app/dumps/example.json': Could not load spid_cie_oidc_entity.FetchedEntityStatement(pk=117): value too long for type character varying(2048)

 django.db.utils.DataError: Problem installing fixture '/app/dumps/example.json': Could not load spid_cie_oidc_entity.FetchedEntityStatement(pk=118): value too long for type character varying(2048)

 django.db.utils.DataError: Problem installing fixture '/app/dumps/example.json': Could not load spid_cie_oidc_entity.FetchedEntityStatement(pk=119): value too long for type character varying(2048)

django.db.utils.DataError: Problem installing fixture '/app/dumps/example.json': Could not load spid_cie_oidc_authority.FederationDescendant(pk=2): value too long for type character varying(33)

**Comment by peppelinux** [comment]
It seems an Heroku issue, do you have to customize the settings fot that?
Unfortunately I never used Heroku

**Comment by peppelinux** [comment]
I can give you assistence, get in touch in slack developers italia channel spid-openid to have a look at this

**Comment by peppelinux** [comment]
@alessia7 did you have any update for this issue?

**Comment by alessia7** [comment]
No, sorry.

**Comment by peppelinux** [comment]
I would like to solve and close this issue, how can I help you?
