### ISSUE TITLE
jwks tool

### ISSUE THREAD

**Issue by MdreW** [italia/spid-cie-oidc-django#246]
quando viene creato un nuovo jwks deve essere aggiunta la chiave , "use": "sig"

**Comment by peppelinux** [comment]
not sure, a jwks can have a specific scope (usage -> sig, enc) or not

it's up to the user add, or not add, the use claims in the jwk

**Comment by peppelinux** [comment]
so as you done in the PR below, the use claim is optional
https://github.com/italia/spid-cie-oidc-django/pull/247/files
