### ISSUE TITLE
Bad request response when send request for new access token using refresh token

### ISSUE THREAD

**Issue by lorenzotaccogna** [italia/spid-cie-oidc-django#261]
When send a request to token endpoint for new access token using refresh token, all works fine at first time, but when we retry request with new resfresh token obtained, token endpoint returns Bad Request error.
If we manually delete revoked issued token, all works fine. 
It seems to be an error when provider endpoint try to get correct issued token.

**Comment by rglauco** [comment]
fixed in https://github.com/italia/spid-cie-oidc-django/releases/tag/v0.9.0
