### ISSUE TITLE
docker-prepare.sh

### ISSUE THREAD

**Issue by alex-webloomit** [italia/spid-cie-oidc-django#266]
While applying the rewrite rules, I think thant

"sed -e $SUB_WTA examples/wallet_trust_anchor/wallet_trust_anchor/**settingslocal.py.example** > $EXPFOLDER/wallet_trust_anchor/wallet_trust_anchor/settingslocal.py"

_should be instead_

"sed -e $SUB_WTA examples/wallet_trust_anchor/wallet_trust_anchor/**settingslocal.py** > $EXPFOLDER/wallet_trust_anchor/wallet_trust_anchor/settingslocal.py"

**Comment by peppelinux** [comment]
temo che l'errore sia la presenza di settingslocal.py piuttosto che settingslocal.py.example

quindi la PR riparatoria deve aggiungere settingslocal.py in gitignore e aggiungere settingslocal.py.example

che ne pensate?

**Comment by rglauco** [comment]
sono d'accordo, ho inserito la riga in .gitignore nella PR attualmente aperta
