### ISSUE TITLE
"Deny consent" returns to a page of the OP

### ISSUE THREAD

**Issue by lucamontano98** [italia/spid-cie-oidc-django#274]
Good afternoon,
I would like to tell you that when I'm going to deny consent I see OP not returning to my RP callback page, but to the same URL on OP domain. I obtain the same problem when I use the preconfigured RP. Can it be fixed? Thanks.

Luca Montano

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/spid-cie-oidc-django/releases/tag/v1.1.2
