### ISSUE TITLE
Trust Anchor in claim trust_marks_issuers

### ISSUE THREAD

**Issue by carlotafuro** [italia/spid-cie-oidc-django#278]
HI,
in the claim **trust_marks_issuers** contained in the Entity Configuration of the Trust Anchor
(http://trust-anchor.org:8000/.well-known/openid-federation?format=json)
I expected to find Trust Anchor itself among the values listed, like this:

```
"trust_marks_issuers": {
  "http://trust-anchor.org:8000": [
    "http://trust-anchor.org:8000"
  ],
  "https://www.spid.gov.it/certification/rp/public": [
    "https://registry.spid.agid.gov.it",
    "https://public.intermediary.spid.it"
  ],
  "https://www.spid.gov.it/certification/rp/private": [
    "https://registry.spid.agid.gov.it",
    "https://private.other.intermediary.it"
  ],
  "https://sgd.aa.it/onboarding": [
    "https://sgd.aa.it"
  ]
},
```
_see file [https://github.com/italia/spid-cie-oidc-django/blob/main/examples/federation_authority/dumps/example.json](https://github.com/italia/spid-cie-oidc-django/blob/main/examples/federation_authority/dumps/example.json)_

Is it implied that the Trust Anchor can issue trust marks?

Thanks for your kind response
Carlo Tafuro

**Comment by peppelinux** [comment]
yes, TM can issue TM and enable other federation entity do so if they are listed in the trust_mark_issuers object
