### ISSUE TITLE
federation resolve endpoint

### ISSUE THREAD

**Issue by carlotafuro** [italia/spid-cie-oidc-django#279]
Why the "**federation_resolve_endpoint**" endpoint is missing in all the entities configuration relating to the entities listed in endpoint list of the Trust Anchor?

- http://relying-party.org:8001/.well-known/openid-federation?format=json
- http://trust-anchor.org:8000/oidc/op/.well-known/openid-federation?format=json
- http://trust-anchor.org:8000/oidc/rp/.well-known/openid-federation?format=json
- http://cie-provider.org:8002/oidc/op/.well-known/openid-federation?format=json

for example for entity relying-party.org:8001 I expected to find:

```
"federation_entity": {
        "federation_resolve_endpoint": "http://relying-party.org:8001/resolve/",
}
```
Thanks for your kind response
Carlo Tafuro

**Comment by peppelinux** [comment]
It Is missing in the example EC of those entity

Please if you like the idea, add these in dumps and do a pull request

I would be pleased to get your contribution on this project
