### ISSUE TITLE
Example Cie provider has the same org name as spid provider

### ISSUE THREAD

**Issue by matteo-s** [italia/spid-cie-oidc-django#295]
The example distributed is configured from dumps with the same organization name "SPID OIDC identity provider" as the SPID provider embedded in the trust anchor. The result is that when listing federation entities those 2 have the same name and are not easily distinguishable. Sorry for nitpicking.

https://github.com/italia/spid-cie-oidc-django/blob/b7b28a8fbb59076dc8d7ba389383379282547315/examples/provider/dumps/example.json#L150

https://github.com/italia/spid-cie-oidc-django/blob/b7b28a8fbb59076dc8d7ba389383379282547315/examples/federation_authority/dumps/example.json#L351

**Comment by rglauco** [comment]
Fixed in https://github.com/italia/spid-cie-oidc-django/commit/535547302ba40dc22e212c75fcab26f0f7c2f997
