### ISSUE TITLE
Errore python3 manage.py

### ISSUE THREAD

**Issue by ErikScandola** [italia/spid-cie-oidc-django#299]
Seguendo la guida presente a questo link https://github.com/italia/spid-cie-oidc-aspnetcore/blob/main/SAMPLE.md, sto provando ad avviare il docker per creare un ambiente di test. Avviandolo c'è un primo problema, ossia il comando di copy nel Dockerfile:
`COPY ["Spid.Cie.OIDC.AspNetCore/Spid.Cie.OIDC.AspNetCore.csproj", "Spid.Cie.OIDC.AspNetCore/"]`

Questo l'ho risolto copiando il progetto presente in `src` all'interno della cartella `samples/1_SimpleSPWebApp`. A questo punto il comando `docker-compose up` fa il suo lavoro ma, solamente il container `spid-cie-oidc-django-main-aspnetcore.relying-party.org-1` riesce a rimanere attivo mentre gli altri quattro si spengono subito. L'errore che trovo in console è il seguente:
`python3: can't open file '/django-project/manage.py': [Errno 2] No such file or directory`

L'errore è legato ai container `spid-cie-oidc-django-main-wallet.trust-anchor.org-1`, `spid-cie-oidc-django-main-relying-party.org-1` e `spid-cie-oidc-django-main-cie-provider.org-1`. Per `spid-cie-oidc-django-main-trust-anchor.org-1` non ho informazioni relative ad errori. Forse questo si deve chiudere e basta? Forse si chiude perché cadono gli altri tre?

**Comment by peppelinux** [comment]
l'errore è ` python3: can't open file '/django-project/manage.py': [Errno 2] No such file or directory`

ti consiglio di avviare il compose di django oidc django eppoi configurare il RP aspnetcore separatamente oppure aprire la issue sul repo aspnetcore
