### ISSUE TITLE
Trust mark validation endpoint issues

### ISSUE THREAD

**Issue by mattebit** [italia/spid-cie-oidc-django#308]
When validating the trust marks, the `trust_mark_status` endpoint of the trust anchor is only supporting POST requests and needs a django CSRF protection token to be processed, is this intended?
For example, in the [spid-cie-oidc-docs](https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/esempi.html#en-5-trust-mark-status-request) the example of the trust mark status request doesn't include any CSRF protection header.

In [openid-federation](https://openid.net/specs/openid-federation-1_0.html#name-trust-mark-status-request) the trust mark status request must be made using a GET method when client authentication is not used. Will this GET method alternative be available?

**Comment by peppelinux** [comment]
According to the federation specs, the trust marks status endpoint doesn't require CSRF protection

we can enable GET Method with a PR

This has produced a regression in the italian specs:
https://bitbucket.org/openid/connect/pull-requests/699#Lopenid-federation-1_0.xmlF3625T3643

**Comment by peppelinux** [comment]
please give me a week to resolve this before our final decision of this issue

**Comment by peppelinux** [comment]
Resolved also here: https://bitbucket.org/openid/connect/pull-requests/704
