### ISSUE TITLE
[Docs] Relying Party: How to load identity provider metadata 

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-django#46]
How to create a SPID/CIE Button

1. configure idps `OIDCFED_IDENTITY_PROVIDERS = ["http://127.0.0.1:8000/oidc/op/"]` in settings.py
2. fetch `manage.py fetch_openid_providers --start`
3. open the landing page of the RP in the browser

**Comment by peppelinux** [comment]
I just added this commit
https://github.com/peppelinux/spid-cie-oidc-django/commit/4bfb33d72734c2eb945dd4fa3e2a325c5a751e46

The documentation must be done here:
https://github.com/peppelinux/spid-cie-oidc-django/blob/dev/docs/technical_specifications/RELYING_PARTY.md

**Comment by peppelinux** [comment]
https://github.com/peppelinux/spid-cie-oidc-django/blob/dev/docs/technical_specifications/RELYING_PARTY.md#oidc-federation-cli

**Comment by francescatronconi** [comment]
Done here https://github.com/italia/spid-cie-oidc-django/pull/149
