### ISSUE TITLE
Revocation Token Response status code != 200

### ISSUE THREAD

**Issue by francescatronconi** [italia/spid-cie-oidc-django#74]
The endpoint is protected by private key jwt so unattacher can't brute force or predict a refresh token.
Having said this we propose to answer even with other http status code different from 200

**Comment by damikael** [comment]
According to:
https://datatracker.ietf.org/doc/html/rfc7009#section-2.2.1
the error response must be compliant to the definition in:
https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

So in case of errors it should present HTTP status code 400.

**Comment by francescatronconi** [comment]
Done here https://github.com/italia/spid-cie-oidc-django/pull/119
