### ISSUE TITLE
[Feat] [Provider] Metadata validation with warning on unsupported sign/enc algs

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-django#83]
in entity.settings we defined the allowd algs

but in federation entity configuration we don't check if in the submitted metadata we have some values not supported.

TODO: log a warning message to the user or raise a ValidationError

**Comment by francescatronconi** [comment]
Done here https://github.com/italia/spid-cie-oidc-django/pull/119/commits/ca44f8942e561ab1a58b4e4723c67f71086111ad
