### ISSUE TITLE
Failed to load example dump for federation_authority example project

### ISSUE THREAD

**Issue by freddi301** [italia/spid-cie-oidc-django#94]
at this stage

https://github.com/italia/spid-cie-oidc-django/blob/546ba2c7f973c980835d10100fb6a5767d55a870/docs/SETUP.md?plain=1#L69

following error occurs

```
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'spid_cie_oidc_provider_oidcsession' with primary key '1' has an invalid foreign key: spid_cie_oidc_provider_oidcsession.user_id contains a value '1' that does not have a corresponding value in spid_cie_oidc_accounts_user.id.
```

**Comment by freddi301** [comment]
workaround: place this file extracted file in `spid-cie-oidc-django/examples/federation_authority/`

[db.zip](https://github.com/italia/spid-cie-oidc-django/files/8214273/db.zip)

**Comment by peppelinux** [comment]
we won't upload any database as binary file in github, i pruned the rp and op sessions, so you won't have any exceptions on FK on missing users, in the DB

https://github.com/italia/spid-cie-oidc-django/releases/tag/v0.4.5

feel free to close this issue when you've done :+1:
