### ISSUE TITLE
Error in settings.py in realying_party example project

### ISSUE THREAD

**Issue by freddi301** [italia/spid-cie-oidc-django#96]
https://github.com/italia/spid-cie-oidc-django/blob/7cfa8d775ee46e24efdc5ecfd32f7f39fb018149/examples/relying_party/relying_party/settings.py#L53

possible solution ?
```
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
```

**Comment by peppelinux** [comment]
thank you @freddi301 

we fixed that yesterday, here
https://github.com/italia/spid-cie-oidc-django/commit/eb2241827dd5752486cd1d39398e6cbf9ce567e7

**Comment by alessia7** [comment]
I get the updated project but I have the same issue. How can I solve it?

**Comment by peppelinux** [comment]
I read
https://github.com/italia/spid-cie-oidc-django/blob/main/examples/relying_party/relying_party/settingslocal.py.example#L56

please update your settingsloca.py with the updated example in settingslocal.py.example

**Comment by peppelinux** [comment]
The problem is that this should be there
https://github.com/italia/spid-cie-oidc-django/blob/main/examples/relying_party/relying_party/settings.py#L50

Soon a patch, thank you

**Comment by peppelinux** [comment]
Done here:
https://github.com/italia/spid-cie-oidc-django/pull/160/files#diff-834f786aa769b369dfb8c6c523b569b256c627baa90467b0cbab144d3ae60899
